### PR TITLE
1 timeout

### PR DESCRIPTION
**Pull request by twekberg**
Noah, I don't know if a call to self.reset() is needed, so I left it out.

### CODE REVIEW

**Comment by twekberg** [comment]
nhoffman@ Hold off on this pull request. I'm doing testing and will need to make a couple of changes before it is ready.

**Comment by twekberg** [comment]
@nhoffman Hold off on this pull request. I'm doing testing and will need to make a couple of changes before it is ready.

**Comment by twekberg** [comment]
@nhoffman I'm ready for review and merge. I have tested good cases and error cases.

**Comment by nhoffman** [comment]
Thanks, @twekberg. Looks good. I will tag a new release.

**Pull request merged**
